package com.techevents.domain.service;

import com.techevents.domain.model.Event;
import com.techevents.domain.port.in.CreateEventUseCase;
import com.techevents.domain.port.in.GetEventsUseCase;
import com.techevents.domain.port.out.EventRepositoryPort;

import java.util.List;
import java.util.UUID;

public class EventService implements CreateEventUseCase, GetEventsUseCase {

    private final EventRepositoryPort eventRepositoryPort;

    public EventService(EventRepositoryPort eventRepositoryPort) {
        this.eventRepositoryPort = eventRepositoryPort;
    }

    @Override
    public Event createEvent(Event event) {
        // Business logic (e.g., validation) could go here
        if (event.getId() == null) {
            // Re-creating the event with a new ID if not present (simulating immutability or ID assignment)
            // Or assume the ID is generated by the caller or the persistence layer.
            // For domain purity, we often generate IDs in the service or use a factory.
             event = new Event(UUID.randomUUID(), event.getTitle(), event.getDescription(), event.getDate(), event.getLocation());
        }
        return eventRepositoryPort.save(event);
    }

    @Override
    public List<Event> getAllEvents() {
        return eventRepositoryPort.findAll();
    }
}
